### ISSUE TITLE
Docházka na událost

### ISSUE THREAD

**Issue by vosecek** [vosecek/tymycz#27]
Lze měnit vlastní účast i po skončení události.

**Comment by vosecek** [comment]
@rhopp Nelze replikovat, opravdu jde o skončené události?

**Comment by rhopp** [comment]
Ee... jde o udalosti nadchazejici, ale po uzaverce. Ale hadam, ze tohle by melo osetrit spis API...

**Comment by vosecek** [comment]
Ok, bude opraveno v dalsi verzi.

**Comment by vosecek** [comment]
Opraveno
