### ISSUE TITLE
Caste "unauthorized" s verzi 1.0.0.

### ISSUE THREAD

**Issue by rhopp** [vosecek/tymycz#37]
Kdyz aplikace bezi na pozadi (neni ukoncena) a po nejake dobe se otevre, tak pri kazdem prechodu z jednoho view na jakykoliv jiny vyskoci "unauthorized" hlaska a nezobrazuje zadne data dokud se clovek sam neprihlasi znovu.
Slovy jineho spoluhrace:
```nemate posledni dobou problemy s appkou tymy? Semtam mi nereaguje a jen vyhodi hlasku 'unauthorised'. Po resetu zas bezi ale je to otravne....co? Nebo je to systemova chyba mezi klavesnici a zidli?```
Ja ten problem mam taky.

**Comment by vosecek** [comment]
Je to dost možný, oprava bude verzí 2.0.0, kde budou i ankety. Dělat se na ni zacne brzy, kompletně přepsané do Ionic 2/Angular 4. Začnu mozna uz dnes :)

**Comment by vosecek** [comment]
Beru zpet, ono to nesouvisí s verzí 1.0.0, ale ve stejném čase API změnilo chování a na vypršelý token už vrací správný HTTP stavový kod, namísto Not logged in, na které se spoléhalo. Opravím.

**Comment by vosecek** [comment]
Opraveno. Diky.
